<?php
include("../config.php");
?>
 <pre>
 <font face=Verdana size=1>
ACCEPTANCE OF TERMS 
Welcome to <?php echo $BLOG_DOMAIN;?>. <?php echo $BLOG_DOMAIN;?> offers various web-based services that allow users to create and update their own weblogs and web journals, including, but not limited to the <?php echo $BLOG_DOMAIN;?> service and other services, including, but not limited to <?php echo $BLOG_DOMAIN;?>, which allow users to post comments upon weblogs, <?php echo $BLOG_DOMAIN;?> our online network of professional weblog developers and users (in this Terms of Use, we refer to the <?php echo $BLOG_DOMAIN;?>,  as the "Services"). The Services may be used through a web browser or by the use of downloadable software clients, including without limitation, our Movable Type software (the "Software"). Please read the following Terms of Service (the "TOS") carefully before using this Site, opening a <?php echo $BLOG_DOMAIN;?> membership account (an "Account") or using the Services so that you are aware of your legal rights and obligations with respect to <?php echo $BLOG_DOMAIN;?> and its affiliates and subsidiaries (collectively, "we," "us," "our," or "<?php echo $BLOG_DOMAIN;?>"). By using this Site, the Services or the Software, you signify your irrevocable acceptance of this TOU. 

Please note that your use of certain Services such as <?php echo $BLOG_DOMAIN;?> is subject to additional Terms of Service, and you agree to such additional Terms of Service when you use those Services or create an Account for those Services. You can review the most current version of the Terms of Service for <?php echo $BLOG_DOMAIN;?> by clicking here at any time.

<?php echo $BLOG_DOMAIN;?> reserves the right to update and change the TOU from time to time without notice or acceptance by you. 

LIMITED LICENSE 
<?php echo $BLOG_DOMAIN;?> grants you a limited license to access and use the Site subject to the terms and conditions of this TOS. However, this license does not allow you to make any commercial use or any derivative use of this Site (including any of its individual elements or content), except as may otherwise be permitted herein from time to time. 

You may not use, frame or utilize framing techniques to enclose the Site, or any individual element or materials within the Site, including without limitation, <?php echo $BLOG_DOMAIN;?> trademarks, logos or other proprietary information (including any Materials (defined below), the content of any text, or the layout and design of any page or form contained on a page) without <?php echo $BLOG_DOMAIN;?> express written consent. Further, you may not use any circumvention tools, meta tags or any other "hidden text" utilizing a <?php echo $BLOG_DOMAIN;?> name, trademark, URL, or product name without <?php echo $BLOG_DOMAIN;?>'s express written consent.

If you accept the End User License Agreement, you will be granted a limited license to install and use the Software subject to its terms and conditions.

USE OF MATERIALS 
All materials transmitted or published by <?php echo $BLOG_DOMAIN;?> on this Site (including, but not limited to the Software, text, images, forms, logos, graphics, images, audio clips, video clips, photographs, illustrations, video and audio clips, etc.) (collectively, the "Materials") are owned or controlled by <?php echo $BLOG_DOMAIN;?>, its subsidiaries or affiliated companies or a third-party provider, and are protected by United States and international copyright laws.

Any copying, uploading, reproduction, transmittal or redistribution of the Materials which is not in accordance with this TOS is strictly prohibited. Making modifications to the Materials (unless such modifications are allowed through the Site, the Services or the Software) or creating derivative works based on the Materials is prohibited, as is the unauthorized use of the Materials on any networked computer environment or other website.

ADDITIONAL REQUIREMENTS TO USE THIS SITE AND THE SERVICES 
In order to use the Services, you must obtain access to the World Wide Web, either directly or through devices that access web-based content, and pay any service fees associated with such access. In addition, you must provide all equipment necessary to make such connection to the World Wide Web, including a computer and modem or other access device. You also understand and agree that the Services may include advertisements and that these advertisements are necessary for <?php echo $BLOG_DOMAIN;?> to provide the Services. Unless explicitly stated otherwise, any new features, updates or upgrades that augment or enhance the Software and/or Services, including the release of new <?php echo $BLOG_DOMAIN;?> properties, shall be subject to this TOS and other Terms of Service, as applicable. You agree not to access the Services by any means other than through the interfaces that are provided by <?php echo $BLOG_DOMAIN;?> for use in accessing the Services.

ACCOUNTS 
REGISTRATION 
In order to use portions of this Site, the Software and/or the Services, you must register with <?php echo $BLOG_DOMAIN;?> to open an Account. As part of the registration process, you will select a user name and password for your Account. You promise you will not (a) select or use a user name of another person with the intent to impersonate that person; (b) use a name subject to the rights of any other person without authorization; (c) use a user name that <?php echo $BLOG_DOMAIN;?>, in its sole discretion, deems inappropriate or offensive; or (d) breach any representation, warranty or promise made by you in this TOS regarding your Account. Users under 13 years of age are required to have a parent or guardian review and complete the registration process.

You are responsible for maintaining the confidentiality of your user name, password and Account, and are fully responsible for all activities that occur under your password or account You agree to (a) immediately notify <?php echo $BLOG_DOMAIN;?> of any unauthorized use of your password or Account or any other breach of security, and (b) ensure that you exit from your Account at the end of each session. <?php echo $BLOG_DOMAIN;?> cannot and will not be liable for any loss or damage arising from your failure to comply with this Section 5. It is your sole responsibility to protect your user name and password and not share your password with any other people. Accordingly, you understand and agree that you shall be liable for any activity performed by any people using the Site, the Software or the Services under your user name and password.

In consideration of use of this Site and the Services, you agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Services's registration form, and (b) maintain and promptly update your Account information to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or <?php echo $BLOG_DOMAIN;?> has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, <?php echo $BLOG_DOMAIN;?> has the right to suspend or terminate your Account and refuse any and all current or future use of this Site, the Software and/or the Services (or any portion thereof). 

Registering an Account for certain features of the Services may require the submission of a credit card number as well as other information such as your email address or mailing address. 

TERMINATION 
You agree <?php echo $BLOG_DOMAIN;?>, in its sole discretion, may terminate your password, and/or Account, and remove and discard any Content within this Site or the Services for any reason, including, without limitation, the lack of use, or if <?php echo $BLOG_DOMAIN;?> believes that you have violated or acted inconsistently with the letter or spirit of this TOS or any additional Terms of Service. Any contracts, verbal or written or assumed, in conjunction with your deleted Content, at <?php echo $BLOG_DOMAIN;?>'s discretion, will be terminated as well. <?php echo $BLOG_DOMAIN;?> may also in its sole discretion and at any time, discontinue providing this Site, the Software and/or the Services, or any part thereof, with or without notice. You agree that any termination of your access to this Site, the Software or Service under any provision of this TOS or any additional Terms of Service may be effected without prior notice, and acknowledge and agree that <?php echo $BLOG_DOMAIN;?> may immediately deactivate or delete your Content, as applicable, and all related information and files. <?php echo $BLOG_DOMAIN;?> reserves the right to bar any further access to such files, this Site, the Software or the Services. You agree that <?php echo $BLOG_DOMAIN;?> shall not be liable to you or any third-party for any termination of your access to this Site, the Software or the Services. Paid Accounts that are terminated will not be refunded.

<?php echo $BLOG_DOMAIN;?> PRIVACY POLICY 
All user information submitted to register an Account and certain other information about you is subject to our Privacy Policy, the terms of which are incorporated into this TOS by reference. 

CONTENT AND CONDUCT RULES AND OBLIGATIONS 
You understand that all information, data, text, software, music, sound, photographs, graphics, video, messages, goods, products, services or other materials ("Content") are the sole responsibility of the person from which such Content originated. This means that you, and not <?php echo $BLOG_DOMAIN;?>, are entirely responsible for all Content that you upload, post, transmit or otherwise make available via this Site or the Services. <?php echo $BLOG_DOMAIN;?> does not control the Content posted via this Site or the Services and, as such, does not guarantee the accuracy, integrity or quality of such Content. The user posting any Content represents that such user has all rights necessary to post such Content without violation of any intellectual property or other rights or any laws or regulations. 

You understand that by using this Site or the Services, you may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances will <?php echo $BLOG_DOMAIN;?> be liable in any way for any Content, including, but not limited to, for any errors or omissions in any Content, or for any loss or damage of any kind incurred as a result of the use of any Content posted, transmitted or otherwise made available via this Site or the Services. You acknowledge that <?php echo $BLOG_DOMAIN;?> does not pre-screen Content, but that <?php echo $BLOG_DOMAIN;?> and its designees shall have the right (but not the obligation) in their sole discretion to refuse or move any Content that is available via this Site or the Services. Without limiting the foregoing, <?php echo $BLOG_DOMAIN;?> and its designees shall have the right to remove any Content that violates this TOS or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Content created by <?php echo $BLOG_DOMAIN;?> or submitted to <?php echo $BLOG_DOMAIN;?>. You acknowledge and agree that <?php echo $BLOG_DOMAIN;?> may preserve Content and may also disclose Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce this TOS or any additional Terms of Service; (c) respond to claims that any Content violates the rights of third-parties; or (d) protect the rights, property, or personal safety of <?php echo $BLOG_DOMAIN;?>, its users and the public. 

You understand that the technical processing and transmission of the Software and the Services, and Content you have submitted through the Services, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.

Should Content be found or reported to be in violation with, but not limited to, the following terms, it will be in <?php echo $BLOG_DOMAIN;?>'s sole discretion as to what action should be taken.

You agree that you will not: 

(a) upload, post, transmit or otherwise make available any Content that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy (up to, but not excluding any address, email, phone number, or any other contact information without the written consent of the owner of such information), hateful, or racially, ethnically or otherwise objectionable; 
(b) harm minors in any way; 
(c) impersonate any person or entity, including, but not limited to, a <?php echo $BLOG_DOMAIN;?> official, forum leader, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity; 
(d) forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Services; 
(e) upload, post or otherwise transmit any Content that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements); 
(f) upload, post or otherwise transmit any Content that infringes any patent, trademark, trade secret, copyright, rights of privacy or publicity, or other proprietary rights of any party; 
(g) upload, post, or transmit unsolicited commercial email or "spam". This includes unethical marketing, advertising, or any other practice that is in any way connected with "spam", such as (a) sending mass email to recipients who haven't requested email from you or with a fake return address, (b) promoting a site with inappropriate links, titles, descriptions, or (c) promoting your site by posting multiple submissions in public forums that are identical; 
(h) upload, post or otherwise transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; 
(i) interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Services; 
(j) intentionally or unintentionally violate any applicable local, state, national or international law, including, but not limited to, regulations promulgated by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange, including without limitation, the New York Stock Exchange, the American Stock Exchange or the NASDAQ, and any regulations having the force of law;
(k) "stalk" or otherwise harass another; 
(l) promote or provide instructional information about illegal activities, promote physical harm or injury against any group or individual, or promote any act of cruelty to animals. This may include, without limitation, providing instructions on how to assemble bombs, grenades and other weapons or incendiary devices; 
(m) offer for sale or sell any item, good or service that (a) violates any applicable federal, state, or local law or regulation, (b) you do not have full power and authority under all relevant laws and regulations to offer and sell, including all necessary licenses and authorizations, or (c) <?php echo $BLOG_DOMAIN;?> determines, in its sole discretion, is inappropriate for sale through the Services provided by <?php echo $BLOG_DOMAIN;?>; 
(n) use the Site or the Services as a forwarding service to another website;
(o) Allow usage by others in such a way as to violate these TOS or any additional Terms of Service; 
(p) take any steps to interfere with or in any manner compromise any of <?php echo $BLOG_DOMAIN;?>'s security measures;
(q) use the Software or this Site for fraudulent purposes;
(r) harvest or collect any information about or regarding other Account holders, including, without limitation, any personal data or information;
(s) sell, lend, lease, trade, rent, barter, sublicense, assign, transfer, or grant rights in any manner to your Account, or password, including, without limitation, on or through the use of any third party web site or service;
(t) copy the Software (other than as provided under United States copyright laws);
(u) remove any proprietary notices from this Site, the Software or any copy thereof;
(v) cause, permit or authorize the modification, creation of derivative works, or translation of this Site or the Software without the express permission of <?php echo $BLOG_DOMAIN;?>;
(w) sell, assign, rent, lease, act as a service bureau, or grant rights in the Software including, without limitation, through sublicense, to any other person or entity;
(x) export or re-export the Software in violation of United States export laws; 
(y) attempt to decompile, reverse engineer, disassemble, modify or hack this Site or the Software, or to defeat or overcome any encryption and/or digital rights management technology implemented by <?php echo $BLOG_DOMAIN;?> with respect to this Site, the Software and/or data transmitted, processed or stored by <?php echo $BLOG_DOMAIN;?>, this Site or the Software;
(z) use this Site or the Software for any commercial purpose or for the benefit of any third party or in any manner not permitted by this TOS, or otherwise exceed the scope of the Services that you have signed up for (i.e., by accessing and using the tools that you do not have a right to use).

If any user is reported to be in violation with the letter or spirit of this TOS for any Term, <?php echo $BLOG_DOMAIN;?> retains the right to terminate such account at any time without further warning.

ADDITIONAL SOFTWARE 
With respect to any additional Software that may be made available by <?php echo $BLOG_DOMAIN;?>, including in connection with this Site or the Services, if you elect to download or access such additional Software, you understand that you may have to agree to additional terms and conditions before you use such Software. 

INTERNATIONAL USE 
Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content. Specifically, you agree to comply with all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside. 

CONTENT SUBMITTED 
<?php echo $BLOG_DOMAIN;?> does not claim ownership of the Content you upload, place or post through this Site or the Services. By uploading, placing or posting Content through this Site or the Services, you grant <?php echo $BLOG_DOMAIN;?> a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing and promoting such Content on <?php echo $BLOG_DOMAIN;?>'s Internet properties. This license exists only for as long as you continue to be a <?php echo $BLOG_DOMAIN;?> customer and shall be terminated at the time your Account is terminated. You acknowledge that <?php echo $BLOG_DOMAIN;?> does not pre-screen Content, but that <?php echo $BLOG_DOMAIN;?> and its designees shall have the right (but not the obligation) in their sole discretion to refuse or remove any Content that is available via the Services. Without limiting the foregoing, <?php echo $BLOG_DOMAIN;?> and its designees shall have the right to remove any Content that violates this TOS or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. 

ADVERTISERS. 
Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through this Site or the Services, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. You agree that <?php echo $BLOG_DOMAIN;?> shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on this Site or the Services. 

LINKS 
This Site or the Services may provide, or third parties may provide, links to other World Wide Web sites or resources. Because <?php echo $BLOG_DOMAIN;?> has no control over such sites and resources, you acknowledge and agree that <?php echo $BLOG_DOMAIN;?> is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any Content, advertising, products, or other materials on or available from such sites or resources. You further acknowledge and agree that <?php echo $BLOG_DOMAIN;?> shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Content, goods or services available on or through any such site or resource. 

INDEMNITY 
You agree to indemnify and hold <?php echo $BLOG_DOMAIN;?>, and its subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any alleged claim or demand, including reasonable attorney fees, made by any third party due to or arising out of your Content, your use of this Site, the Software or the Services, your connection to this Site or the Services, your violation of this TOS or any additional Terms of Service, or your violation of any rights of another, whether you are a registered user or not. The user is solely responsible for his or her actions when using this Site, the Software or the Services, including, but not limited to, costs incurred for Internet access.

RESALE OF SERVICES 
You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Services, use of the Services, or access to the Services without the express permission by <?php echo $BLOG_DOMAIN;?>. 

GENERAL PRACTICES REGARDING USE AND STORAGE 
You acknowledge that <?php echo $BLOG_DOMAIN;?> may establish general practices and limits concerning use of this Site, the Software or Services and may modify such practices and limits from time to time. 

MODIFICATIONS TO THIS SITE, THE SOFTWARE AND THE SERVICES 
<?php echo $BLOG_DOMAIN;?> reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, this Site, the Software and/or the Services (or any part thereof) with or without notice at any time. You agree that <?php echo $BLOG_DOMAIN;?> shall not be liable to you or to any third party for any modification, suspension or discontinuance of this Site, the Software and/or the Services. 

NOTIFICATION OF COPYRIGHT INFRINGEMENT 
<?php echo $BLOG_DOMAIN;?> may be required to disclose information to individuals asserting rights under the Digital Millennium Copyright Act, and you expressly authorize <?php echo $BLOG_DOMAIN;?> to comply with any and all lawful notices, subpoenas, court orders or warrants without prior notice to you.

<?php echo $BLOG_DOMAIN;?> will investigate notices of copyright infringement and take appropriate actions. If you believe that your work has been used or copied in a way that constitutes copyright infringement and such infringement is occurring on or through this Site, please notify <?php echo $BLOG_DOMAIN;?>. 

<?php echo $BLOG_DOMAIN;?> PROPRIETARY RIGHTS 
You acknowledge and agree that this Site, the Software and the Service may contain proprietary and confidential information that is protected by applicable laws governing intellectual property, proprietary rights and the like. All <?php echo $BLOG_DOMAIN;?> code and specifications, and all other code and specifications for the Software and the operation of the Services, are subject to their express or implied licenses.

Submission of Unsolicited Ideas and Information 

<?php echo $BLOG_DOMAIN;?> does not want to receive confidential or proprietary information from you through this Site or by email. Unless otherwise agreed in writing by an authorized <?php echo $BLOG_DOMAIN;?> representative, any material, information or idea you transmit to <?php echo $BLOG_DOMAIN;?> by any means may be disseminated or used by <?php echo $BLOG_DOMAIN;?> or its affiliates without compensation or liability to you for any purpose whatsoever, including, but not limited to, developing, manufacturing and marketing products. However, this provision does not apply to Content (as defined herein), or to personal information that is subject to our Privacy Policy.



DISCLAIMER OF WARRANTIES 

YOU EXPRESSLY UNDERSTAND AND AGREE THAT:

(a) YOUR USE OF THIS SITE, THE SOFTWARE AND THE SERVICES IS AT YOUR SOLE RISK. THIS SITE, THE SOFTWARE AND THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. <?php echo $BLOG_DOMAIN;?> EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
(b) <?php echo $BLOG_DOMAIN;?> IS NOT RESPONSIBLE FOR ANY DAMAGE, LOSS OF DATA, CUSTOMER INFORMATION OR VENDOR DATA, REVENUE, OR OTHER HARM TO BUSINESS ARISING OUT OF DELAYS, MISDELIVERY OR NONDELIVERY OF INFORMATION, RESTRICTION OR LOSS OF ACCESS, BUGS OR OTHER ERRORS, UNAUTHORIZED USE DUE TO YOUR SHARING OF ACCESS TO THIS SITE, THE SOFTWARE OR THE SERVICES, OR OTHER INTERACTION WITH THIS SITE, THE SOFTWARE OR THE SERVICES. YOU ARE RESPONSIBLE FOR MAINTAINING AND BACKING-UP YOUR DATA AND INFORMATION THAT MAY RESIDE ON THIS SITE OR THE SERVICES. <?php echo $BLOG_DOMAIN;?> DOES NOT WARRANT THAT (i) THIS SITE, THE SOFTWARE OR THE SERVICES WILL MEET YOUR SPECIFIC REQUIREMENTS, (ii) THIS SITE, THE SOFTWARE OR THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THIS SITE, THE SOFTWARE OR THE SERVICES WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THIS SITE, THE SOFTWARE OR THE SERVICES WILL MEET YOUR EXPECTATIONS, (v) THIS SITE, THE SOFTWARE, THE SERVICES AND/OR THE SERVER THAT MAKES SAME AVAILABLE ARE FREE OF VIRUSES, CLOCKS, TIMERS, COUNTERS, WORMS, SOFTWARE LOCKS, DROP DEAD DEVICES, TROJAN-HORSES, ROUTINGS, TRAP DOORS, TIME BOMBS OR ANY OTHER HARMFUL CODES, INSTRUCTIONS, PROGRAMS OR COMPONENTS, AND (vi) ANY ERRORS IN THIS SITE OR THE SOFTWARE WILL BE CORRECTED.
(c) ANY MATERIAL OR CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THIS SITE, THE SOFTWARE OR THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.
(d) NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED THROUGH OR FROM THIS SITE, THE SOFTWARE OR THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS TOU OR OTHER TERMS OF SERVICE. 

LIMITATION OF LIABILITY 
YOU EXPRESSLY UNDERSTAND AND AGREE THAT <?php echo $BLOG_DOMAIN;?> SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF <?php echo $BLOG_DOMAIN;?> HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THIS SITE, THE SOFTWARE OR THE SERVICES; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THIS SITE, THE SOFTWARE OR THE SERVICES; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THIS SITE OR THE SERVICES; OR (v) ANY OTHER MATTER RELATING TO THIS SITE, THE SOFTWARE OR THE SERVICES. 

YOUR ONLY RIGHT WITH RESPECT TO ANY PROBLEMS OR DISSATISFACTION WITH THIS SITE, THE SERVICES OR THE SOFTWARE IS TO TERMINATE YOUR ACCOUNT, DISCONTINUE ANY USE OF THIS SITE AND CEASE USE OF THE SERVICES AND THE SOFTWARE.

EXCLUSIONS AND LIMITATIONS 
SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS OF SECTIONS 19 AND 20 MAY NOT APPLY TO YOU. 
</font>
</pre>

