<?php
$arrSpace = array();
$arrLimit = array();
$arrPackages = array();

$tablePackages = DataTable("blog_packages","");

while($tablePackage = mysql_fetch_array($tablePackages))
{
	$arrPackages[$tablePackage["id"]] = $tablePackage["traffic"];
}

$tableUsers = DataTable("admin_users","WHERE username <> 'administrator' ");

while($tableUser = mysql_fetch_array($tableUsers))
{
	$arrSpace[$tableUser["username"]] = 0;
	
	if(isset($arrPackages[$tableUser["plan"]]))
	{
		$arrLimit[$tableUser["username"]] = $arrPackages[$tableUser["plan"]];
	}
	else
	{
		$arrLimit[$tableUser["username"]] = 0;
	}

}

$strWhere = "";

if(isset($ProceedApply))
{
 	if($code == "1")
	{
	
	}
	else
	if($code == "2")
	{
		$strWhere = " WHERE date>=".mktime(0, 0, 0, date("m")-1, date("d"),   date("Y"))." ";
	}
	else
	if($code == "3")
	{
		$strWhere = " WHERE date>=".mktime(0, 0, 0, date("m")-2, date("d"),   date("Y"))." AND date<= ".mktime(0, 0, 0, date("m")-1, date("d"),   date("Y"))."";
	}
	else
	if($code == "4")
	{
		$strWhere = " WHERE date>=".strtotime("-1 month")."";
	}
	else
	if($code == "5")
	{
		$strWhere = " WHERE date>=".strtotime("-1 week")."";
	}
	else
	if($code == "6")
	{
		$strWhere = " WHERE date>=".strtotime("-1 day")."";
	}
}

$tableBands = DataTable("blog_band",$strWhere);

while($tableBand = mysql_fetch_array($tableBands))
{

	if (array_key_exists($tableBand["user"], $arrSpace)) 
	{
		$arrSpace[$tableBand["user"]] += $tableBand["size"];
	}
}


?>

	<table summary="" border="0" width="100%">
  				<tr>
  					<td width="40"><img src="images/icons2/download.gif" width="39" height="39" alt="" border="0"></td>
  					<td><b>User sites bandwidth</b></td>
  				</tr>
  			</table>
			
<form action=index.php method=post>
<input type=hidden name=ProceedApply>
<input type=hidden name=action value="<?php echo $action;?>">
<input type=hidden name=category value="<?php echo $category;?>">

<table summary="" border="0" width=100%>
	<tr>
		<td>
		<br>
		<b>Traffic generated by the user sites for time period:

		
		<select name=code>
			<option value=1 <?php if(isset($code)&&$code==1) echo "selected";?>>All</option>
			<option value=2 <?php if(isset($code)&&$code==2) echo "selected";?>>This Calendar Month</option>
			<option value=3 <?php if(isset($code)&&$code==3) echo "selected";?>>Previous Calendar Month</option>
			<option value=4 <?php if(isset($code)&&$code==4) echo "selected";?>>Last 1 Month</option>
			<option value=5 <?php if(isset($code)&&$code==5) echo "selected";?>>Last 1 Week</option>
			<option value=6 <?php if(isset($code)&&$code==6) echo "selected";?>>Last 1 Day</option>
		</select>
		&nbsp;&nbsp;
		<input type=submit value=" Show " class=adminButton>
		</b>
		</form>
		<br><br><br>
		
		<center>
		<table width="100%" cellspacing="0" cellpadding="2" style="border-width:1px 1px 1px 1px;border-color:#cecfce;border-style:solid">
	<?php
		
		$bFlag = true;
		arsort($arrSpace);
		foreach($arrSpace as $key=>$value)
		{
		
			$iKB= round($value/1024);
			
			$fontColor = "#de4700";
			
			if($iKB > $arrLimit[$key])
			{
							echo 
							"
								<tr height=26 bgcolor=#de4700>
							";
							
							$fontColor = "#000000";
			}
			else
			{
							echo 
							"
								<tr height=26 bgcolor=".($bFlag?"#efebef":"#ffffff").">
							";
			}
			
			echo "
				<td>&nbsp;<b>$key</b></td>
				<td width=150><font color=$fontColor><b>".$iKB."KB</b></font></td>
			</tr>
			";
			
			$bFlag = !$bFlag;
		}
		
		?>
		
		
		</table>
		</center>
		
		</td>
	</tr>
</table>
<br><br>
<?php

?>




